<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_File Uploader_drag-drop-upload</name>
   <tag></tag>
   <elementGuidId>dff05da1-723e-4965-9141-bfa1643f8b11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='drag-drop-upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#drag-drop-upload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>38538be4-0639-42f6-b384-584835db7ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dz-success-mark dz-clickable</value>
      <webElementGuid>1184f643-278f-4d49-bc90-e8d0c079fdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag-drop-upload</value>
      <webElementGuid>dd5fedbb-37bb-4038-8906-2b17df2c3158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag-drop-upload&quot;)</value>
      <webElementGuid>01ca4b1e-24b0-4379-873b-0f36e0ed15e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='drag-drop-upload']</value>
      <webElementGuid>5d23cd3e-9957-4247-a013-3ff1acb00781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]</value>
      <webElementGuid>55be5c45-6dbf-4204-bd5b-65b02c91e06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploader'])[1]/following::div[1]</value>
      <webElementGuid>4d242389-7a1c-4f09-9a14-de5d499dfeaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[1]/preceding::div[3]</value>
      <webElementGuid>0c70241a-fc9c-428a-ac3e-f13dc1540ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>7e03804a-3ef4-4de9-b100-1cd9b95f0687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'drag-drop-upload']</value>
      <webElementGuid>c8709a31-b809-4b88-9587-ecb7ec502ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
